id: P010424
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG25383
  title: སྐར་མའི་གོ་ལའི་སྟེང་དུ་ཕྱིན་པ།
  author: ''
  volumes:
    ec293a8ae2b84ce38440bf3386507576:
      image_group_id: I1KG25385
      title: ''
      volume_number: 1
      total_pages: 256
      base_file: v001.txt
