id: I44DD6852
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T02:46:23+00:00'
last_modified: '2022-06-08T13:30:24.030386+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25383
  title: སྐར་མའི་གོ་ལའི་སྟེང་དུ་ཕྱིན་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    68E6:
      image_group_id: I1KG25385
      title: ''
      total_pages: 256
      order: 1
      base_file: 68E6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
